app = 'pilatescomplete-bot'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'data'
  destination = '/var/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
